version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: ptitmeet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ptitmeet_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ptitmeet_net

  redis:
    image: redis:alpine
    container_name: ptitmeet_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ptitmeet_net

  livekit:
    image: livekit/livekit-server:latest
    container_name: ptitmeet_livekit
    command: --dev --bind 0.0.0.0
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    depends_on:
      - redis
    networks:
      - ptitmeet_net

volumes:
  mysql_data:

networks:
  ptitmeet_net:
    driver: bridge